# Generated by Django 4.2.3 on 2024-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubs_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
