# Generated by Django 4.2.3 on 2024-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_messages_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
