# Generated by Django 4.2.3 on 2024-11-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_messages_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='updated_on',
        ),
    ]
