# Generated by Django 4.2.3 on 2024-11-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_remove_messages_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='updated_on',
        ),
    ]
