# Generated by Django 5.1.2 on 2024-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_clubs_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
