# Generated by Django 5.1.2 on 2024-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_clubs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='description',
            field=models.TextField(default='This Is A Club'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(default='Enter Description'),
        ),
    ]
